basePath: /
definitions:
  entity.Delivery:
    properties:
      address:
        type: string
      city:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      region:
        type: string
      zip:
        type: string
    type: object
  entity.Item:
    properties:
      brand:
        type: string
      chrt_id:
        type: integer
      name:
        type: string
      nm_id:
        type: integer
      price:
        type: integer
      rid:
        type: string
      sale:
        type: integer
      size:
        type: string
      status:
        type: integer
      total_price:
        type: integer
      track_number:
        type: string
    type: object
  entity.Model:
    properties:
      customer_id:
        type: string
      date_created:
        type: string
      delivery:
        $ref: '#/definitions/entity.Delivery'
      delivery_service:
        type: string
      entry:
        type: string
      internal_signature:
        type: string
      items:
        items:
          $ref: '#/definitions/entity.Item'
        type: array
      locale:
        type: string
      oof_shard:
        type: string
      order_uid:
        type: string
      payment:
        $ref: '#/definitions/entity.Payment'
      shardkey:
        type: string
      sm_id:
        type: integer
      track_number:
        type: string
    type: object
  entity.Payment:
    properties:
      amount:
        type: integer
      bank:
        type: string
      currency:
        type: string
      custom_fee:
        type: integer
      delivery_cost:
        type: integer
      goods_total:
        type: integer
      payment_dt:
        type: integer
      provider:
        type: string
      request_id:
        type: string
      transaction:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: https://docs.google.com/document/d/1f1Ni6u5mi4If5iyVMLQHjIAZJltDZc0QCGawitSSbxI/edit
  title: Nats-streaming consumer
  version: "1.0"
paths:
  /model:
    get:
      consumes:
      - application/json
      description: method to select model by uid
      parameters:
      - description: uid заказа
        format: email
        in: query
        name: uid
        required: true
        type: string
      responses:
        "200":
          description: Ok
          schema:
            type: string
      summary: get model by uid
  /models:
    get:
      consumes:
      - application/json
      description: method to select models
      responses:
        "200":
          description: Ok
          schema:
            type: string
      summary: get models
  /send-model:
    post:
      consumes:
      - application/json
      description: method to send model
      parameters:
      - description: Объект model
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/entity.Model'
      responses:
        "200":
          description: Ok
          schema:
            type: string
      summary: send model
swagger: "2.0"
